name: ci
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/cached-venv
    - name: Test krakenpull service
      run: |
        source venv/bin/activate
        black krakenpull --check --diff --color
        mypy krakenpull --ignore-missing-imports
        pytest -vv

  publish:
    name: Publish to pypi.org
    if: github.event.ref == 'refs/heads/main'
    needs: [ tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history so semantic-release can resolve commits
          token: ${{ secrets.CICD_RELEASE_GITHUB_TOKEN }}
      - uses: ./.github/actions/cached-venv
      - name: Create github release
        uses: python-semantic-release/python-semantic-release@v9.10.1
        with:
          changelog: true
          commit: true
          push: true
          tag: true
          vcs_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry config pypi-token.pypi "$PYPI_TOKEN"
          poetry publish --build
